# Generated by Django 4.1.2 on 2022-11-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_lance_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lance',
            name='valor',
            field=models.FloatField(),
        ),
    ]
